name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Changez cela si votre branche principale a un autre nom
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'  # Modifiez selon votre version de Java

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean verify

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ajoutez votre token SonarQube dans les secrets de votre dépôt
        run: mvn sonar:sonar -Dsonar.projectKey=squ_f44dd17dddccc10ce3cbde364d0196536f063339 -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONAR_TOKEN
